ci: build and release

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -12,40 +12,43 @@ jobs:
       fail-fast: false
       matrix:
         build: [
-          # {name: canturin, platform: linux/amd64, os: ubuntu-latest},
+          {platform: linux/amd64, os: ubuntu-latest},
           # {name: wailsTest, platform: windows/amd64, os: windows-latest},
-          {name: wailsTest, platform: darwin/universal, os: macos-latest}
+          # {name: wailsTest, platform: darwin/universal, os: macos-latest}
         ]
     runs-on: ${{ matrix.build.os }}
+
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+      - name: Linux Discovery
+        if: runner.os == 'Linux'
+        id: linux_discovery
+        run: |
+          sudo apt-get -yq update
+          DISTRO=$(lsb_release -rs) # Get the distribution version (e.g., "22.04", "24.04")
+          if [[ "$DISTRO" == "20.04" ]]; then
+            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
+          elif [[ "$DISTRO" == "22.04" ]]; then
+            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
+          elif [[ "$DISTRO" == "24.04" ]]; then
+            sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
+          else
+            echo "Unsupported Linux distribution: $DISTRO"
+            exit 1 # Fail the workflow if the distribution is not supported
+          fi
+          echo "DISTRO=$DISTRO" >> "$GITHUB_OUTPUT"
+        shell: bash
+
+      - name: Setup Go
+        uses: actions/setup-go@v5
         with:
-          submodules: recursive
-      - uses: ./.github/actions/build
-        with:
-          build-name: ${{ matrix.build.name }}
-          build-platform: ${{ matrix.build.platform }}
+          go-version: '1.24'
 
-# jobs:
-#   build-and-release:
-#     strategy:
-#       matrix:
-#         # os: [ubuntu-latest, macos-latest, windows-latest]
-#          os: [ubuntu-latest]
-         
-#     runs-on: ${{ matrix.os }}
+      - name: Install Wails3
+        run: |
+          go install github.com/wailsapp/wails/v3/cmd/wails3@latest
+          wails3 doctor
+        shell: bash
 
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v4
-
-#       - name: Set up Go
-#         uses: actions/setup-go@v5
-#         with:
-#           go-version: '1.24'
-
-#       - name: Install wails3
-#         run: go install github.com/wailsapp/wails/v3/cmd/wails3@latest
-
-#       - name: Test
-#         run: wails3 doctor
